### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by alainib** [Widen/i18next-async-backend#4]
Hello
i cannot use this cannot with yarn v3 

i get this error 

```
/path_to_my_project/.pnp.cjs:33675
      Error.captureStackTrace(firstError);
            ^

Error: Missing "./lib" export in "i18next-async-backend" package
Require stack:
- /path_to_my_project/src/server/middlewares/serveLocales.js
- /path_to_my_project/src/server/entrypoint.js
- /path_to_my_project/entrypoint.js
    at Function.require$$0.Module._resolveFilename (/path_to_my_project/.pnp.cjs:33675:13)
    at Function.require$$0.Module._load (/path_to_my_project/.pnp.cjs:33529:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/path_to_my_project/src/server/middlewares/serveLocales.js:21:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/path_to_my_project/.yarn/cache/pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at require$$0.Module._extensions..js (/path_to_my_project/.pnp.cjs:33719:33)
    at Object.newLoader [as .js] (/path_to_my_project/.yarn/cache/pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (/path_to_my_project/.pnp.cjs:33559:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/path_to_my_project/src/server/entrypoint.js:26:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

how to fix it ? 
it was working with yarn v2.4.3
(edit) node v16.13.2 

thank you.

**Comment by mskelton** [comment]
What version of the package are you using and what version of Node are you using?

**Comment by alainib** [comment]
sorry. 
i'm on v16.13.2  ( with nvm, i was on 17 before but same error and even cannot just start the project)

thank's for help

**Comment by mskelton** [comment]
What version of the package are you using?

**Comment by alainib** [comment]
damn sorry

 "i18next-async-backend": "1.0.1"

**Comment by mskelton** [comment]
Thanks, let me see if I can reproduce it.

**Comment by alainib** [comment]
thanks

i have almost the same error with yarn `3.2.0` and  "i18next-async-backend": "^1.0.2"

**Comment by mskelton** [comment]
Is your project using ESM?

**Comment by alainib** [comment]
the code is full JS, no ECMAScript written

**Comment by mskelton** [comment]
ECMAScript modules.  `import _ from ''` vs `const _ = require()`.

https://nodejs.org/api/esm.html

When I tested locally using ESM, the package fails to load with the exact error you reference.

**Comment by alainib** [comment]
yes i use import 

import fs from 'fs';
import path from 'path';

**Comment by mskelton** [comment]
I opened a PR to convert this package to ESM only which is the direction much of the ecosystem is moving.  Thanks for bringing this to my attention!

**Comment by alainib** [comment]
thank you very much for help and time :)

**Comment by mskelton** [comment]
The fix for this has been released in [v2.0.0](https://github.com/Widen/i18next-async-backend/releases/tag/v2.0.0).

**Comment by alainib** [comment]
thanks for the fix.
i still get this error unfortunatly 

i upgraded to  `yarn v3.2.0` and checked in `.yarn/cache/i18next-async-backend-npm-2.0.0-d21f8424f6-4a6f61c58a.zip`  that the "2.0.0" is well installed

i try to remove  `.yarn/cache` and run `yarn install`, same error :( 

what i'm doing wrong ? 
thank you 


yarn 3.2.0
node 16.13.2
npm 8.1.2

**Comment by mskelton** [comment]
Not much I can do without a reproduction.  After the changes I made things work fine for me.  Could you put together a public GitHub repo that reproduces the issue?
