### ISSUE TITLE
`Cannot find module 'i18next-async-backend'` in Jest

### ISSUE THREAD

**Issue by graup** [Widen/i18next-async-backend#7]
Hi! This is working great in development but for some reason, in the jest test environment it fails to import the package. There is no problem with any other package.

Has anyone seen this issue before?

```
Cannot find module 'i18next-async-backend' from 'src/configs/i18n.ts'

> 4 | import AsyncBackend from 'i18next-async-backend';

at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
at Object.<anonymous> (src/configs/i18n.ts:4:1)
```

```
package.json

"i18next": "^21.8.2",
"i18next-async-backend": "^2.0.0",
"jest": "^26.4.0",
```

**Comment by graup** [comment]
Solved by upgrading Jest to the latest version.

Sorry for the noise.
